### ISSUE TITLE
Catch the error when connection is refused

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#7] opened 2019-05-02 15:42 UTC
Hi !

Actually, when the server is down, we have a very big red error displayed.

Maybe it could be cool to catch this error ? Instead of this big red error, on two right panel, under `__roast_pretty__` and / or `__roast_headers__` a message from the roast plugin could be displayed like:

« Message generated by the roast plugin: connection refused. Maybe the server is down.  »

It's not a very big problem ;-). 

Following the roast file than display the error.
```
# Assume than there is not server running on port 8082
GET http://localhost:8082
```

Thanks you very much for your plugin !

**Comment by sharat87** [comment] 2019-06-05 10:39
Yeah, I myself wanted this for so long. It's now fixed. When an error like that occurs, we only get a 1-3 lines summary of the error, not the whole stack trace.

**Closed by sharat87** 2019-06-05 10:39 UTC
Labels: bug

**Comment by JulioJu** [comment] 2019-06-23 12:34
@sharat87  sorry for the delay.

No, actually, when connection is refused we have still the stacktrace

**Comment by sharat87** [comment] 2019-09-09 02:42
I am not able to reproduce this. With the current version, I only get a small message relating to the error, not the whole stack trace. Can you test again with the current master and if you still see the problem, please open a new issue and mention this one there.

Thank you.
